const cards = [
  {
    id: 1,
    title: "Phi phi, khai islands tour with speed boat full day",
    slug: "phi-phi-khai-islands-tour-with-speed-boat-full-day",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "30",
    category: "Tours",
    isFavorite: false,
    isBasket: false,
    starCount: "4.3",
    commentCount: "20",
    location: "Phuket",
    oldPrice: "1,020",
    price: "1,400",
    theme: "Island Tour",
    activity: "Swimming",
    vehicle: "Yacht",
    features: ["Transfer", "Halal Food"],
    startTime: "08:00",
    groupSize: 20,
  },
  {
    id: 2,
    title: "Bangkok City and Temples Tour",
    slug: "bangkok-city-and-temples-tour",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "25",
    category: "Tours",
    isFavorite: true,
    isBasket: false,
    starCount: "4.7",
    commentCount: "35",
    location: "Bangkok",
    oldPrice: "800",
    price: "1,000",
    theme: "Land Tour",
    activity: "Running",
    vehicle: "Speedboat",
    features: ["Vegetarian Food"],
    startTime: "09:00",
    groupSize: 15,
  },
  {
    id: 3,
    title: "Chiang Mai Elephant Sanctuary Visit",
    slug: "chiang-mai-elephant-sanctuary-visit",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "20",
    category: "Rent",
    isFavorite: false,
    isBasket: false,
    starCount: "4.9",
    commentCount: "50",
    location: "Chiang Mai",
    oldPrice: "1,500",
    price: "1,800",
    theme: "Safari",
    activity: "Elephant Care",
    vehicle: "Safari",
    features: ["Transfer"],
    startTime: "07:00",
    groupSize: 10,
  },
  {
    id: 4,
    title: "Phuket Island Hopping Adventure",
    slug: "phuket-island-hopping-adventure",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "15",
    category: "Rent",
    isFavorite: true,
    isBasket: false,
    starCount: "4.5",
    commentCount: "40",
    location: "Phuket",
    oldPrice: "2,000",
    price: "2,300",
    theme: "Island Tour",
    activity: "Snorkelling",
    vehicle: "Catamaran",
    features: ["Halal Food"],
    startTime: "10:00",
    groupSize: 25,
  },
  {
    id: 5,
    title: "Ayutthaya Historical Park Tour",
    slug: "ayutthaya-historical-park-tour",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "10",
    category: "Tickets",
    isFavorite: false,
    isBasket: false,
    starCount: "4.8",
    commentCount: "25",
    location: "Ayutthaya",
    oldPrice: "900",
    price: "1,100",
    theme: "Land Tour",
    activity: "Running",
    vehicle: "Speed Catamaran",
    features: ["Transfer"],
    startTime: "06:00",
    groupSize: 30,
  },
  {
    id: 6,
    title: "Krabi 4 Islands Tour",
    slug: "krabi-4-islands-tour",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "35",
    category: "Transfer",
    isFavorite: true,
    isBasket: false,
    starCount: "4.6",
    commentCount: "30",
    location: "Krabi",
    oldPrice: "1,200",
    price: "1,500",
    theme: "Island Tour",
    activity: "Snorkelling",
    vehicle: "Yacht",
    features: ["Halal Food"],
    startTime: "11:00",
    groupSize: 50,
  },
  {
    id: 7,
    title: "Pattaya Coral Island Tour",
    slug: "pattaya-coral-island-tour",
    imageSrc:
      "https://www.travelandleisure.com/thmb/nDDNqO2EctQhiIfZrxeXTF47zhE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/TAL-koh-phi-phi-PLACESTHAILAND1023-09b9d347b3cd4844b4ae19e4e06a9a6d.jpg",
    discount: "40",
    category: "Tours",
    isFavorite: false,
    isBasket: false,
    starCount: "4.4",
    commentCount: "45",
    location: "Pattaya",
    oldPrice: "1,000",
    price: "1,300",
    theme: "Land Tour",
    activity: "Running",
    vehicle: "Speedboat",
    features: ["Vegetarian Food", "Halal Food"],
    startTime: "12:00",
    groupSize: 60,
  },
];

export default cards;
